language: node_js
branches:
  only:
  - master
  - "/^greenkeeper/.*$/"
cache: false
notifications:
  email: false
node_js:
- node
script:
- npm run test:prod && npm run build
after_success:
- npm run report-coverage
- npm run deploy-docs
- npm run semantic-release
deploy:
  provider: npm
  email: m@ttjohnston.com
  on:
    repo: johnstonmatt/easy-e
  api_key:
    secure: c0owNROBM+b4eqnj/PLuf1akqDOMupWq5AUnr5OIlq/CJyc9Q6Sr/Pl28/MR3txXucuabYTDwRnIBbwfj9DvG1A2wNp3jgF44fiLxD6S+fw1zwukN9O5ZKiaI2ZP2lfeSyvXtnahswkGWX7PLZDZ1L9gS3W/WPCdsIgLFjRgnBojw4wFYS5weRbsALGB1udtNCZB9tuPqIIiIj/BznIOfP12QdcKLaQZMmc92GeHhJ5OF9R2IWuDQ2vidTMGxhig6SdJrIG/VbkPONsHw3Va8k45xW5t48Ub5WJpaXfhu+P10pKXVRaa81s4dWGBTdwSpUt6/WjF8VY1eQgj5cy5cnOcsEzALJp+NEE9ckT98PQ/Av8Hv9ZBt5705g3mDYdakDfRA2/SHeywzWG+wPYShihwcWavJdSxHJ81TzEmw1wQgf9PnBfg2Obp/2q++Eh6xQKPdx2beTZe+lM2pAPkxEA+VyRlIs7i8mBREyAYjp/jk627RiEHzZEE3RX5Oy6XvNWJF/kVQQHAYZ9nHTWA9wth8FH/v2hIfUk+h49CGJKV9vv+QxUUk5UTxsM49ww4LbEhR5I3Pd9/WSlX2DU/vG+xqEql3FhBHgvOf9MjnBLL64Gd3Zh2u1XMgixILI5rkoKztYDmAniMUmU/CqNQTBgQ9pRGSYk4MMVzABMDKyA=
