language: node_js
branches:
  only:
  - master
  - "/^greenkeeper/.*$/"
cache: false
notifications:
  email: false
node_js:
- node
script:
- npm run test:prod && npm run build
after_success:
- npm run report-coverage
- npm run deploy-docs
- npm run semantic-release
deploy:
  provider: npm
  email: m@ttjohnston.com
  on:
    repo: johnstonmatt/easy-e
  api_key:
    secure: RRWf3q4xqn/hbnEC1wymu8G8VctCarF5EPBaNVEbUdlmKMW9H8Mck9TDucjYo8I8VUjptwmdOHQrL0reOFwri1wGEjlAzyNpa5BfSf7nstmD5YsNpaTirg3x09Y7IENRfIWpPsncywFLG8DxSiRGHJVl7o6/sX7TVp1JisUG0nrYtdgX6zNcG6VqPmWf1L1zxIg/PvO6L9R4m50MH4Gi+X8HfBVW9HZAi5drkss4FfB937e3JMRQg74femfiuf+f5zDs+du79rvgaVGe82FwIDbsabnSHAMcowTVT0mrnij86ApQcJYZwgLLKub/cbw27HmotsycDepncaBVZrwryuUJGLJEUGs12e3svuzAwaMgwt8y/ED43zg9g2z8gkbXhxzDb/cHHaaJdgBCCB1cT4f2EH0FZ4vd8MEUpQelF3DwF8XSxM/k+0NvVDPtezct1p7PgdE9tv8NZ0ujRk7nPseN83caPQJan3MDcK6cN2vc8R/YbQqtuvFw+AkghgY9++dcwn/SH0+e5h2Eni3eNQ+cQN5LQsSEDDoqsH4PzwoxZEhgYZK/x9cvZOwVht+BdUkRGaznW3CeNV7nate41QP/psQKi56BYVcAlUULEI2+vr0GE7ALZ1Oq/iHje36Nn2IRHKc/X1bLsIWft4D0fOq6R91mMoP5zSYGESFJ8jU=
