language: node_js
branches:
  only:
  - master
  - "/^greenkeeper/.*$/"
cache: false
notifications:
  email: false
node_js:
- node
script:
- npm run test:prod && npm run build
after_success:
- npm run report-coverage
- npm run deploy-docs
- npm run semantic-release
deploy:
  provider: npm
  email: m@ttjohnston.com
  api_key:
    secure: c3frngU81Z+0c+fT/9xT+txOijannHZnuVxgP++QwFIu5gPDKtsE0R/Q7AME25oK2+sXmMezCz4f6Pfo3WxkYjyr2wKSoc553c5a+qUpVQZruHKyf1PemdulddqpktKDzkGCnNUUnjEq/GKyOKwIclprsep1mV1d+tkMEjdmBnIVrhvyoNqt0iX7FeUOxuVSpfagtvNuGosHI68uzYThKF0JQJl/1Ay/SopjcYjMP9w4SA4ASDUVD0SCC2+Qtp409K94/5hoTCrNlgaomLu2lys7IRpqng+0U5f48VEWZB62jbxn+h8xa/z9rQ6c+R+8tvciQQ7eWzOPt5T4NDw8W+V+EjlXkor7+VxeWZo3wZaNJXEk7CZ1SqfEflVOPBrU8Rxf2zDt2y5LrIPFpbMMFNWb/CuAPXGZimmhNlITKscGr2WJ6g4+eNS7Cp80j7chOt1qCkUkpb7eqS2Ssm0NKB/RqZCUlvXoK+pQd20UxdVuMmPg3AVjBo9yR0hk3RcSuxPSJO/Z/p52NiWGVdduPQwgyO4aYY/sJf0BwENEPmZ09hzOVpfuZIazaZdhrMOBKMZ6baduulR2j6rNUbEM72+YSqu1Qi7wZV7Evj/IDxmC1Dp1OcA4AF+qzI26pUnk2Y0Bzk5Goht+jkgBGbXfsN07Ixxe1Arodi4FukLMryA=
  on:
    repo: johnstonmatt/easy-e
dd:
  secure: CePzAzC2bZFsRIGUHubmBdJtTRph9K0lAf+wixQZghhi21M9qpbcSfrwDhbD+t6edVby2i8hhK5ZMm9OnI85d/pdaDquCbwXC1/PYOexmspQCF4kQ0bJADIpRhSmycriv/7l51aSBe/GAcqJ/Jr9JcE3uRt2uyGaLmHQXM0AMjNLiDfLqNogiwkIH4xxw3CrrjuzW8Uls3rwQwpZHd1qOk05/JTWaUzBuqhA/qvpRpBOsWkfX1+eTXlbpDMOkGaNTDFntKJqDxb178wsqoesjGSSGk1aS3hmd7YzryU+/TfyV6JA7aCXPZOJqqkxJTiMoZ3+S9rGwecDGDmvZceA1VmQQsh5lPfnFtrZTSSIJF4u5ij92ux3EwiIRh+wWe7fBTN9sQgVw4D7iuHoz8kRQZH07+1telW6CKksAQuPS0v+tUzK0yAQ+u610RMLpt82z0cEYDSXZkVZF3ForLOX74bCM0aDEhUuMCirdhDMCuNIEELpXGNGSVst1pJ53XB+2G4V3gfhCDPKiX0XBYjcOTMv9GEkVOzNbNSSGppIcOGgyU4Y/IFtbg843QkqPZ/gC7lPhwZqNRqZWi5OGw+vCKTSHSuM6zna01ct6/59CFo+IQLT+80bKgo8Q5Rf3MRLq7i+vHrCKY8kwDMMTM3v9Tt6o4BjBcjTwdTZBxVqSSg=
